security_controllers:
    resource:
        path: ../src/Security/UserInterface/Controller/
        namespace: App\Security\UserInterface\Controller
    type: attribute
    prefix: /api/security/
    name_prefix: security_
